import{S as v}from"./assets/vendor-CQMm3erF.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))n(s);new MutationObserver(s=>{for(const r of s)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function o(s){const r={};return s.integrity&&(r.integrity=s.integrity),s.referrerPolicy&&(r.referrerPolicy=s.referrerPolicy),s.crossOrigin==="use-credentials"?r.credentials="include":s.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(s){if(s.ep)return;s.ep=!0;const r=o(s);fetch(s.href,r)}})();(()=>{const t={openModalBtn:document.querySelector("[data-menu-open]"),closeModalBtn:document.querySelector("[data-menu-close]"),links:document.querySelectorAll(".mob-navig .mobile-menu-link"),modal:document.querySelector("[data-modal]")};console.log(t.closeModalBtn),t.openModalBtn.addEventListener("click",o),t.closeModalBtn.addEventListener("click",e),t.links.forEach(s=>{console.log(s),s.addEventListener("click",n)});function e(){t.modal.classList.add("is-hidden"),t.openModalBtn.classList.remove("is-hidden"),t.closeModalBtn.classList.add("is-hidden")}function o(){console.log(t.modal),t.modal.classList.remove("is-hidden"),t.openModalBtn.classList.add("is-hidden"),t.closeModalBtn.classList.remove("is-hidden")}function n(s){t.modal.classList.add("is-hidden"),t.openModalBtn.classList.remove("is-hidden"),t.closeModalBtn.classList.add("is-hidden")}})();async function g(t){try{const e=await fetch(`https://sound-wave.b.goit.study/api/artists?limit=8&page=${t}`);if(!e.ok){const o=await e.text();throw new Error(`HTTP ${e.status}: ${o}`)}return await e.json()}catch(e){throw console.error("Помилка при запиті:",e),e}}const y="/project-PushIt_Js/assets/icons-Cx4ZaPhk.svg",a={artistsList:document.querySelector(".artists-cards-list"),loadMoreBtn:document.querySelector(".load-more")};let l=1,f=0;B();a.loadMoreBtn.addEventListener("click",S);a.artistsList.addEventListener("click",M);function M(t){if(t.target.classList.contains("artist-learn-more-btn")){const o=t.target.closest(".artist-card").dataset.id;console.log("Clicked artist ID: ",o)}}async function L(t){const e=t.map(({genres:o,strArtist:n,strBiographyEN:s,strArtistThumb:r,_id:i})=>{const u=Array.isArray(o)?o.map(b=>`<li class="artist-genre-item">${b}</li>`).join(""):"",c=k(s);return`
        <li class="artist-card"  data-id="${i}">
          <div class="artist-thumb">
      <img src="${r}" alt="${n}" class="artist-img">
          </div>
          <ul class="aritist-genre-list">${u}</ul>
              <h3 class="artist-name">${n}</h3>
              <p class="artist-bio">${c}</p>
            <button type="button" class="artist-learn-more-btn">Learn More
              <svg class="artist-btn-icon" width="24" height="24" fill="#fff">
                  <use href="${y}#icon-learn-more"></use>
              </svg>
          </button>
         </li>     `}).join("");a.artistsList.insertAdjacentHTML("beforeend",e)}async function B(){try{const t=await g(l);if(t.artists.length===0){d(),console.log("Порожній список!");return}if(L(t.artists),f=Math.ceil(t.totalArtists/8),l>=f){d(),console.log("Сторінок більше, ніж контенту!");return}}catch(t){console.log("Помилка:",t.message),d();return}}async function S(){l+=1;try{const t=await g(l);if(t.artists.length===0){d(),console.log("Список артистів порожній!");return}if(L(t.artists),l>=f){d(),console.log("Сторінок більше, ніж контенту!");return}$()}catch(t){console.log("Помилка:",t.message);return}}function $(){if(!a.artistsList.firstElementChild)return;const{height:t}=a.artistsList.firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}function k(t){return t.length<=140?t:t.slice(0,140)+"..."}function d(){a.loadMoreBtn.classList.add("is-hidden")}const E=document.querySelector(".swiper-wrapper");async function q(){try{const e=await(await fetch("https://sound-wave.b.goit.study/api/feedbacks?limit=3&page=2")).json();console.log("API response:",e);const o=j(e.data);E.innerHTML=o,new v(".swiper",{loop:!0,centeredSlides:!1,spaceBetween:0,pagination:{el:".swiper-pagination",clickable:!0},navigation:{nextEl:".right_btn",prevEl:".left_btn"},scrollbar:{el:".swiper-scrollbar"}})}catch(t){console.error("Fetch error:",t)}}function P(t){return`
    <div class="fb_item swiper-slide">
      <div class="stars">${C(t.rating)}</div>
      <p class="fb_user_text">"${t.descr}"</p>
      <p class="fb_user_name">${t.name}</p>
    </div>
  `}function j(t){return t.map(e=>P(e)).join("")}function C(t){let e="";for(let n=1;n<=5;n++){const s=n<=t?"icon-purple-star":"icon-white-star";e+=`
      <svg width="20" height="20">
        <use href="${y}#${s}"></use>
      </svg>
    `}return e}document.addEventListener("DOMContentLoaded",()=>{q()});const m=document.querySelector(".left_btn"),p=document.querySelector(".right_btn");function w(){window.innerWidth>=768?(m.style.display="flex",p.style.display="flex"):(m.style.display="none",p.style.display="none")}w();window.addEventListener("resize",w);refs.feedbackModalBtn.addEventListener("click",feedbackModalServise.open);async function T(){const t=document.querySelector(".images-1"),e=document.querySelector(".images-2");try{const n=await(await fetch("https://sound-wave.b.goit.study/api/artists?limit=20&page=1")).json(),r=await(await fetch("https://sound-wave.b.goit.study/api/artists?limit=20&page=3")).json(),i=n.artists.map(c=>c.strArtistThumb),u=r.artists.map(c=>c.strArtistThumb);t.innerHTML=h(i),e.innerHTML=h(u)}catch(o){console.error(o.message)}}function h(t){return t.map(e=>`<img src="${e}"/>`).join("")}T();
//# sourceMappingURL=index.js.map
