import{S as d}from"./assets/vendor-CQMm3erF.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function r(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(t){if(t.ep)return;t.ep=!0;const o=r(t);fetch(t.href,o)}})();(()=>{const e={openModalBtn:document.querySelector("[data-menu-open]"),closeModalBtn:document.querySelector("[data-menu-close]"),links:document.querySelectorAll(".mob-navig .mobile-menu-link"),modal:document.querySelector("[data-modal]")};console.log(e.closeModalBtn),e.openModalBtn.addEventListener("click",r),e.closeModalBtn.addEventListener("click",s),e.links.forEach(t=>{console.log(t),t.addEventListener("click",n)});function s(){e.modal.classList.add("is-hidden"),e.openModalBtn.classList.remove("is-hidden"),e.closeModalBtn.classList.add("is-hidden")}function r(){console.log(e.modal),e.modal.classList.remove("is-hidden"),e.openModalBtn.classList.add("is-hidden"),e.closeModalBtn.classList.remove("is-hidden")}function n(t){e.modal.classList.add("is-hidden"),e.openModalBtn.classList.remove("is-hidden"),e.closeModalBtn.classList.add("is-hidden")}})();const u="/project-PushIt_Js/assets/icons-0zWjcESH.svg",p=document.querySelector(".swiper-wrapper");async function f(){try{const s=await(await fetch("https://sound-wave.b.goit.study/api/feedbacks?limit=3&page=2")).json();console.log("API response:",s);const r=h(s.data);p.innerHTML=r,new d(".swiper",{loop:!0,centeredSlides:!1,spaceBetween:0,pagination:{el:".swiper-pagination",clickable:!0},navigation:{nextEl:".right_btn",prevEl:".left_btn"},scrollbar:{el:".swiper-scrollbar"}})}catch(e){console.error("Fetch error:",e)}}function m(e){return`
    <div class="fb_item swiper-slide">
      <div class="stars">${g(e.rating)}</div>
      <p class="fb_user_text">"${e.descr}"</p>
      <p class="fb_user_name">${e.name}</p>
    </div>
  `}function h(e){return e.map(s=>m(s)).join("")}function g(e){let s="";for(let n=1;n<=5;n++){const t=n<=e?"icon-purple-star":"icon-white-star";s+=`
      <svg width="20" height="20">
        <use href="${u}#${t}"></use>
      </svg>
    `}return s}document.addEventListener("DOMContentLoaded",()=>{f()});const l=document.querySelector(".left_btn"),c=document.querySelector(".right_btn");function a(){window.innerWidth>=768?(l.style.display="flex",c.style.display="flex"):(l.style.display="none",c.style.display="none")}a();window.addEventListener("resize",a);
//# sourceMappingURL=index.js.map
